import { Open_Sans } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { UserProvider } from "@/lib/context/user";
import './globals.css';
import { HighlightsProvider } from '@/lib/context/highlight';
import CookiePolicy from "@/components/cookiePolicy";
import Head from 'next/head';

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Apjot",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.jpeg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <script async src={`https://www.googletagmanager.com/gtag/js?id=G-BWV7N0MFWX`}></script>
        <script dangerouslySetInnerHTML={{
          __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-BWV7N0MFWX');
          `,
        }} />
      </Head>
      <body className={openSans.className}>
        <UserProvider>
          <HighlightsProvider>
            <Header />
            {children}
            <CookiePolicy/>
            <Footer />
          </HighlightsProvider>
        </UserProvider>


      </body>
    </html>
  );
}
