import { Open_Sans } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { UserProvider } from "@/lib/context/user";
import './globals.css';
import AnalyticsProvider from '@/components/AnalyticsProvider'; 
import { HighlightsProvider } from '@/lib/context/highlight';

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Apjot",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.jpeg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <UserProvider>
          <HighlightsProvider>
            <Header />
            {children}
            <Footer />
          </HighlightsProvider>
        </UserProvider>
      </body>
    </html>
  );
}
